// <auto-generated />
namespace ListaDeCompras.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class criandoprodutoerelacaocomsupermercado : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(criandoprodutoerelacaocomsupermercado));
        
        string IMigrationMetadata.Id
        {
            get { return "202211081638115_criando produto e relacao com supermercado"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
