// <auto-generated />
namespace ListaDeCompras.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class relacionamentolistaproduto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(relacionamentolistaproduto));
        
        string IMigrationMetadata.Id
        {
            get { return "202211091438461_relacionamento lista-produto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
